app/urls.py
from django.contrib import admin
from django.urls import path

import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('video', views.video_content),
    path('profile', views.user_profile),
    path('upload', views.upload_page),
    path('login', views.login_page),
    path('signup', views.signup_page),
    path('search', views.search_page),
    path('explore', views.explore_page)
]

emoticontent/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reelfeels.urls'))
]


# Serve static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reelfeels/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name='home'),
    path('video', views.video_content, name='video-static'),
    path('video/<video_id>', views.video_content, name='video'),
    path('my-profile', views.my_profile, name='my-profile'),
    path('profile/update', views.update_profile, name='profile-update'),
    path('profile/<user_id>', views.user_profile, name='profile'),
    path('upload', views.upload_page, name='upload'),
    path('login', views.login_page, name='login'),
    path('signup', views.signup_page, name='signup'),
    path('search', views.search_page, name='search'),
    path('explore', views.explore_page, name='explore'),
    path('logout', views.logout_page, name='logout'),
    path('video/<pk>/edit', views.VideoUpdate.as_view(), name='video-edit'),
    path('video/<pk>/delete', views.VideoDelete.as_view(), name='video-delete'),
    path('comment/add/<video_id>', views.CommentHandler.add_comment, name='add-comment'),
    path('comment/delete/<video_id>/<comment_id>', views.CommentHandler.delete_comment, name='delete-comment'),
]



sanguinethirst/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reelfeels.urls'))
]


# Serve static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve media files (for development, not production)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reelfeels/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
import uuid
import datetime
from urllib.parse import urlparse
from urllib.parse import parse_qs
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Videos
class Video(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    title = models.TextField(max_length=100, help_text='Insert video title here', verbose_name='Title', default='An Emotional Video!')

    video_link = models.TextField(verbose_name='Link to Video', max_length=1000, help_text='Insert video link here')
    video_description = models.TextField(max_length=1000, verbose_name="Video Description", default='Am I happy? Sad? Disgusting?? Watch me to find out!')

    happiness = models.IntegerField(verbose_name='Global happiness', default=0)
    sadness = models.IntegerField(verbose_name='Global sadness', default=0)
    disgust = models.IntegerField(verbose_name='Global disgust', default=0)
    anger = models.IntegerField(verbose_name='Global anger', default=0)
    surprise = models.IntegerField(verbose_name='Global surprise', default=0)

    last_updated_emotions = models.DateField(null=True, default=datetime.date.today)

    yesterdays_views = models.IntegerField(verbose_name='Yesterdays views', default=0)

    todays_views = models.IntegerField(verbose_name='Todays views', default=0)

    date_shared = models.DateField(blank=False)

    #not in our diagram, but we need some reference to the uploader(User model)
    uploader_id = models.ForeignKey('Profile', on_delete=models.CASCADE)

    class Meta:
        ordering = ["-date_shared"]
        permissions = (
            ("can_edit", "Can edit video"),
        )

    def __str__(self):
        return self.title

    def get_youtube_thumbnail(self):
        return "http://i4.ytimg.com/vi/" + self.video_link + "/0.jpg"

    def get_top_emotion(self):
        emotions = {"none": 0, "happiness": self.happiness, "sadness":self.sadness,
            "disgust":self.disgust, "anger":self.anger, "surprise":self.surprise}
        return max(emotions, key=lambda key: emotions[key])

# TO-DO: find a way to delete this without it breaking (or just check if deleting this is magically okay now)
def profile_filename():
    return 'I exist because there is a weird migration conflict when I am not here'

# Users
class Profile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    user = models.OneToOneField(User, on_delete=models.CASCADE, db_column='user')
    # TO-DO: decide where to put uploaded files
    profile_pic = models.ImageField(upload_to='profile_pictures/', null=True, blank=True, default='profile_pictures/default.png')

    happiness = models.IntegerField(verbose_name='Overall happiness', default=0)
    sadness = models.IntegerField(verbose_name='Overall sadness', default=0)
    disgust = models.IntegerField(verbose_name='Overall disgust', default=0)
    anger = models.IntegerField(verbose_name='Overall anger', default=0)
    surprise = models.IntegerField(verbose_name='Overall surprise', default=0)

    last_updated_emotions = models.DateField(verbose_name='When overall emotions were last calculated', blank=True, null=True)

    def get_username(self, obj):
        return obj.user.username

    @receiver(post_save, sender=User)
    def update_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
        instance.profile.save()

    def __str__(self):
        return self.user.__str__()

    def get_top_emotion(self):
        emotions = {"none": 0, "happiness": self.happiness, "sadness":self.sadness,
            "disgust":self.disgust, "anger":self.anger, "surprise":self.surprise}
        return max(emotions, key=lambda key: emotions[key])

# Emotions for certain videos
class ViewInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    viewer_id = models.ForeignKey('Profile', on_delete=models.CASCADE)
    video_id = models.ForeignKey('Video', on_delete=models.CASCADE)

    last_watched = models.DateField(verbose_name='Date updated', blank=False)

    calculated_happiness = models.IntegerField(verbose_name='Calculated Happiness', default=0)
    calculated_sadness = models.IntegerField(verbose_name='Calculated Sadness', default=0)
    calculated_disgust = models.IntegerField(verbose_name='Calculated Disgust', default=0)
    calculated_anger = models.IntegerField(verbose_name='Calculated Anger', default=0)
    calculated_surprise = models.IntegerField(verbose_name='Calculated Surprise', default=0)

    previous_happiness = models.IntegerField(verbose_name='Previous Happiness', default=0)
    previous_sadness = models.IntegerField(verbose_name='Previous Sadness', default=0)
    previous_disgust = models.IntegerField(verbose_name='Previous Disgust', default=0)
    previous_anger = models.IntegerField(verbose_name='Previous Anger', default=0)
    previous_surprise = models.IntegerField(verbose_name='Previous Surprise', default=0)

    def __str__(self):
        return '"' + self.video_id.title + '" viewed by ' + self.viewer_id.user.username

# Comment for a given video, made by a given user
class Comment(models.Model):
    # I copied the id from the other tables above -- is this fine for comments?
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    video_id = models.ForeignKey('Video', on_delete=models.CASCADE)
    commenter_id = models.ForeignKey('Profile', on_delete=models.CASCADE)

    # TO-DO: decide what (if any) the max_length of a single comment should be
    content = models.TextField(max_length=1000, help_text='Write your comment here!', verbose_name='The text content of a comment')

    def __str__(self):
        return self.content


"""
# The uploads
class Upload(models.Model):
    # I copied the id from the other tables above -- is this fine for uploads?
    id = models.CharField(primary_key=True, default=uuid.uuid4().hex[:8], editable=False, max_length=8)

    video_id = models.OneToOneField('Video', on_delete=models.CASCADE)

    uploader = models.ForeignKey('User', on_delete=models.CASCADE)

    def __str__(self):
        return '"{0}" -- {1}'.format(self.video_id, self.uploader)
"""

reelfeels/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from .models import Video, Profile, Comment, ViewInstance
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class' : 'form-control required', 'placeholder':'Username',}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control required', 'placeholder':'Password',}))

class SignUpForm(UserCreationForm):
    profile_pic = forms.ImageField(required=False)
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Email', 'class' : 'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username', 'class' : 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class' : 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password', 'class' : 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email','password1', 'password2')


#creating the form to allow users to create new comments
class CommentCreationForm(forms.Form):
    comment = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Submit a public comment', 'size': '100', 'maxlength':'1000'}))

# form class for uploading a video
class VideoUploadForm(forms.Form):
    video_url = forms.URLField(widget=forms.URLInput(attrs={'class':'form-control', 'placeholder':'YouTube URL...', 'id':'video-url-input'}))
    video_title = forms.CharField(label='Title:', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Upload Title...'}))
    video_description = forms.CharField(label='Description:', widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Upload Description...', 'id':'upload-desc', 'maxlength':'1000', 'rows':'5'}))


class VideoUpdateForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ( 'title', 'video_description')
        widgets = {
            'title': forms.Textarea(attrs={'cols': 10, 'rows': 2, 'class': 'form-control'}),
            'video_description': forms.Textarea(attrs={'cols': 10, 'rows': 10, 'class': 'form-control'}),
        }
        labels = {
            'title': _('Title'),
            'video_description': _('Description'),
        }

    def clean(self):
        cleaned_data = super(VideoUpdateForm, self).clean()

        title = cleaned_data.get('title')
        video_description = cleaned_data.get('video_description')

        return cleaned_data


class UserUpdateForm(forms.ModelForm):
    email = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control required', 'placeholder':'Username',}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control required'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control required'}))
    class Meta:
        model = User
        fields = ('email', 'username', 'password')

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_pic',)

reelfeels/templates/access_denied.html
<h1> NO!</h1>
<h2>You do not have permission to access this page </h2>

reelfeels/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>reelFeels</title>{% endblock %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSS -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'styles/index.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab|Roboto" rel="stylesheet">

  <!-- favicon-->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">

  {% block customcss %}{% endblock%}

</head>
<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="main-nav">
      <a class="navbar-brand" href="/">
        <img src="../static/images/logo.png" class="logo">
        reel<strong>Feels</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-content">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}" data-navlink="index"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'explore' %}" data-navlink="explore"><i class="fas fa-compass"></i> Explore</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'upload' %}" data-navlink="upload"><i class="fas fa-arrow-circle-up"></i> Upload </a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" onSubmit="return getSearchResults()">
            <input class="form-control mr-sm-2" id="search-query" type="text" placeholder="Search" aria-label="Search">
            <button class="btn my-2 my-sm-0" onclick="return getSearchResults()"><i class="fas fa-search"></i></button>
          </form>

          <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my-profile' %}" data-navlink="my-profile"><i class="fas fa-user"></i> Profile </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i>Log Out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}" id="login-button" data-navlink="login"><i class="fas fa-user"></i> Log In</a>
            </li>
          {% endif %}
          </ul>
        </div>
      </nav>
    </header>

  {% block content %}{% endblock %}
  <footer>
    <div class="row">
      <div class="col-md-12">
        <div class="fake-social-media">
          <a href="https://github.com/mmacquarrie/reelfeels"><i class="fab fa-github"></i></a>
          <a href="https://github.com/mmacquarrie/reelfeels"><i class="fab fa-twitter"></i></a>
          <a href="https://github.com/mmacquarrie/reelfeels"><i class="fab fa-facebook-f"></i></a>
          <a href="https://github.com/mmacquarrie/reelfeels"><i class="fab fa-instagram"></i></a>
        </div>
        <p>Copyright &copy; 2018</p>
      </div>
    </div>
  </footer>

  <!-- SCRIPTS -->
  <!-- <script src="{% static 'scripts/jquery-3.2.1.slim.min.js' %}"></script> below non-slim version required for AJAX functionality-->
  <script src="{% static 'scripts/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
  <script src="{% static 'scripts/navbar.js' %}"></script>
  <script src="{% static 'scripts/font-awesome-all.js' %}"></script>
  <script src="{% static 'scripts/googlecharts.js' %}"></script>
  <script src="https://download.affectiva.com/js/3.2/affdex.js"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script type=text/javascript>
    var searchURL = "{% url 'search' %}"

    function getSearchResults(){
      var searchQuery = document.getElementById('search-query').value;
      if (searchQuery.length > 0)
          self.location.href = searchURL + '?search-query=' + searchQuery;
      else
          self.location.href = searchURL;
      return false;
    }

  </script>

  {% block customjs %}{% endblock%}
</body>
</html>

reelfeels/templates/explore.html
{% extends "base_template.html" %}
{% load filters %}

{% block title %}
<title>Explore</title>
{% endblock %}

{% block customcss %}
{% load static %}
<link rel="stylesheet" href="{% static 'styles/explore.css' %}">
{% endblock %}

{% block content %}
<div class = "container-fluid">
  <div class = "row">

    <!--side bar-->
    <nav class="col-md-2 d-md-block bg-light sidebar filter-sidebar text-center">
      <div class="sidebar-sticky">
        <h2 align="center" class="filter-title"> Filter by</h2>
        <ul class="nav flex-column btn-group btn-group-toggle filter-btn-container text-center">
          <li class="nav-item">
            <label class="btn btn-secondary btn-block active">
              <input class="emo-filter" type="radio" name="emotions" id="all-filter" checked>
              <label for="all-filter">All</label>
            </label>
          </li>
          <li class="nav-item">
            <label class="btn btn-secondary btn-block">
              <input class="emo-filter" type="radio" name="emotions" id="anger-filter">
              <label for="anger-filter">Anger</label>
            </label>
          </li>
          <li class="nav-item">
            <label class="btn btn-secondary btn-block">
              <input class="emo-filter" type="radio" name="emotions" id="disgust-filter">
              <label for="disgust-filter">Disgust</label>
            </label>
          </li>
          <li class="nav-item">
            <label class="btn btn-secondary btn-block">
              <input class="emo-filter" type="radio" name="emotions" id="happiness-filter">
              <label for="happiness-filter">Happiness</label>
            </label>
          </li>
          <li class="nav-item">
            <label class="btn btn-secondary btn-block">
              <input class="emo-filter" type="radio" name="emotions" id="sadness-filter">
              <label for="sadness-filter">Sadness</label>
            </label>
          </li>
          <li class="nav-item">
            <label class="btn btn-secondary btn-block">
              <input class="emo-filter" type="radio" name="emotions" id="surprise-filter">
              <label for="surprise-filter">Surprise</label>
            </label>
          </li>
        </ul>
      </div>
    </nav>

    <!-- New Section -->
    <main role ="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
      {% if new_videos %}
      <div class="new-videos mb-25">
        <h2 class="text-center">New</h2>
        <div class="album">
          <div class="container">
            <div class="row">
              {% for new_video in new_videos %}
              {% with top_emotion=new_video|top_emotion %}
              <div class="col-lg-4 col-md-6 video-container {{top_emotion}} all">
                <div class="card mb-4 box-shadow">
                  <a href="{% url 'video' new_video.id %}">
                    <img class="card-img-top" src="{{new_video|youtube_thumbnail}}">
                  </a>
                  <div class="card-body">
                    <a href="{% url 'video' new_video.id %}"><h6 class="card-text">{{new_video.title}}</h6></a>
                    <div class="d-flex justify-content-between align-items-center">
                      <small><a href="{% url 'profile' new_video.uploader_id.id %}" class="card-link text-secondary">{{new_video.uploader_id.user.username}}</a></small>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                      <small class="text-muted">{{new_video.todays_views}} views</small>
                      <div class="card-link text-secondary">
                        <img class="video-top-emotion" src="{% static 'images/emoticons/'|add:top_emotion|add:'-small.png' %}" alt='{{top_emotion}}'>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endwith %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      {% endif %}

      <!-- Popular Section -->
      {% if popular_videos %}
      <div class="popular-videos mb-25">
        <h2 class="text-center">Popular</h2>
        <div class="album">
          <div class="container">
            <div class="row">
              {% for popular_video in popular_videos %}
              {% with top_emotion=popular_video|top_emotion %}
              <div class="col-lg-4 col-md-6 video-container {{top_emotion}} all">
                <div class="card mb-4 box-shadow">
                  <a href="{% url 'video' popular_video.id %}">
                    <img class="card-img-top" src="{{popular_video|youtube_thumbnail}}">
                  </a>
                  <div class="card-body">
                    <a href="{% url 'video' popular_video.id %}"><h6 class="card-text">{{popular_video.title}}</h6></a>
                    <div class="d-flex justify-content-between align-items-center">
                      <small><a href="{% url 'profile' popular_video.uploader_id.id %}" class="card-link text-secondary">{{popular_video.uploader_id.user.username}}</a></small>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                      <small class="text-muted">{{popular_video.todays_views}} views</small>
                      <div class="card-link text-secondary">
                        <img class="video-top-emotion" src="{% static 'images/emoticons/'|add:top_emotion|add:'-small.png' %}" alt='{{top_emotion}}'>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endwith %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </main>
  </div>
</div>
{% endblock %}

{% block customjs %}
<script src="{% static 'scripts/emo-filter.js' %}"></script>
{% endblock %}

reelfeels/templates/index.html
{% extends "base_template.html" %}

{% block title %}<title>Home</title>{% endblock %}

{% block content %}
<div class="container-fluid" id="home">
  <div class="row buffer-bottom">
    <div class="col-md-12" id="jumbotron-col">
      <div class="jumbotron">
        <div class="jumbotron-overlay ml-auto mr-auto"></div>
        <div class="jumbotron-text">
          <h3 class="display 1" id="tagline">Real people. Real feelings. </h3>
          <p class="lead">Content that's affective.</p>
          <p class="lead">
            <a class="btn btn-dark btn-main btn-lg" id="explore-button" href="{% url 'explore' %}" role="button">Explore!</a>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="row buffer-bottom">
    <div class="col-md-3 ml-md-auto">
      <div class="home-marketing-point">
        <i class="fas fa-heart"></i>
        <h4>Wear your heart on your screen</h4>
        <p>Stop sharing recycled minion memes and start sharing feelings!</p>
      </div>

    </div>
    <div class="col-md-3">
      <div class="home-marketing-point">
        <i class="far fa-smile"></i><br>
        <h4>We'll tell you how you really feel</h4>
        <p>And we definitely won't sell your webcame feed to Cambridge Analytica.</p>
      </div>

    </div>
    <div class="col-md-3 mr-md-auto">
      <div class="home-marketing-point">
        <i class="fas fa-comments"></i><br>
        <h4>Eliminate the noise</h4>
        <p>In an age of troll comments and recycled memes, it's hard to know how people really feel. With reelfeels, the feelings are always real. </p>
      </div>

    </div>
  </div>

  <div class="row" id="user-testimony-block">
    <div class="col-md-4 ml-md-auto mr-md-auto" >
      <h4> Don't ask us, ask our users!</h4>
      <ul id="user-testimonies">
        <li>
          <div class="user-testimony-quote">&ldquo;I like it&rdquo;</div>
          <div class="user-testimony-cite">Someone, hopefully</div>
        </li>
        <li>
          <div class="user-testimony-quote">&ldquo;A+&rdquo;</div>
          <div class="user-testimony-cite">Tim Richards, ideally</div>
        </li>
        <li>
          <div class="user-testimony-quote">&ldquo;Thanks&rdquo;</div>
          <div class="user-testimony-cite">Obama</div>
        </li>
      </ul>
    </div>
  </div>
</div>

{% endblock%}

reelfeels/templates/user-profile.html
{% extends "base_template.html" %}

{% block title %}
<title>User Profile</title>
{% endblock %}

{% block customcss %}
{% load static %}
<link rel="stylesheet" href="{% static 'styles/tab-styles.css' %}">
<link rel="stylesheet" href="{% static 'styles/user-profile.css' %}">
{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4 col-xs-12">
      {% if user.profile_pic %}
        <img src="{{user.profile_pic.url}}" class='profile-pic mx-auto d-block'>
      {% else %}
        <img src="{% static 'media/profile_pictures/default.png' %}" class='profile-pic mx-auto d-block'>
      {% endif %}
      <h4 class="user-details username">{{user.user.username}}</h4>
      <h5 class="user-details">Favorite Emotion: {{user.get_top_emotion}}
        <img src="{% static 'images/emoticons/'|add:user.get_top_emotion|add:'-small.png' %}" class="emoticon">
      </h5>
      {% if is_owner %}
        <div class="video-edit-link-wrap text-center">
          <a href="{% url 'profile-update' %}" class='video-edit-link'><i class="fas fa-edit"></i> Edit Profile</a>
        </div>
      {% endif %}
    </div>
    <div class="col-md-4"></div>
  </div>

  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 col-xs-12">

      <!-- Tabs -->
      <div class="tab">
        <button class="tablinks active" onclick="openTab(event, infoType.feels)" id="defaultOpen">Feels</button>
        <button class="tablinks" onclick="openTab(event, infoType.content)">Content</button>
      </div>

      <!-- Feels -->
      <div id="user-feels" class="tabcontent">
        <div id="user-emotions-chart"></div>
        <p>Joy: <strong id="user-happiness">{{user.happiness}}</strong>%</p>
        <p>Sadness: <strong id="user-sadness">{{user.sadness}}</strong>%</p>
        <p>Disgust: <strong id="user-disgust">{{user.disgust}}</strong>%</p>
        <p>Surprise: <strong id="user-surprise">{{user.surprise}}</strong>%</p>
        <p>Anger: <strong id="user-anger">{{user.anger}}</strong>%</p>
      </div>

      <!-- Content -->
      <div id="user-content" class="tabcontent">
        {% if user.video_set.all %}
        	{% for video in user.video_set.all %}
          <div class="row">
            <div class="col-md-4 col-xs-12">
              <!-- video thumbnail -->
              <a href="{% url 'video' video.id %}">
                <img class="video-thumbnail" src="{{video.get_youtube_thumbnail}}">
              </a>
            </div>
            <div class="col-md-8 col-xs-12 mt-1">
              <!-- video text -->
                <a href="{% url 'video' video.id %}"><h5>{{video.title}}</h5></a>
              <p>{{video.video_description}}</p>
            </div>
          </div>
          <hr>
          {% endfor %}
        {% else %}
          <div class="text-center">
            They haven't uploaded any videos yet :(
          </div>
        {% endif %}
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>
{% endblock %}
{% block customjs %}
<script src="{% static 'scripts/user-profile.js' %}"></script>
{% endblock %}